### ISSUE TITLE
Create and Use Subfolders 

### ISSUE THREAD

**Issue by dasmeet** [marknesh/storage-googledrive-export#12]
Hi!

Is it possible to follow the same folder structure as in the GCS bucket on Drive as well?

Currently, the file is being copied with the complete path as part of the filename.

e.g. GCS: FolderA > FolderB > File.pdf
Drive: "folderA/FolderB/File.pdf"

**Comment by marknesh** [comment]
Hello @dasmeet 

This feature is currently in progress and it will be released in the next update.

**Comment by marknesh** [comment]
@dasmeet Please update to the latest version of the extension in order to use the same folder structure.

**Comment by dasmeet** [comment]
@marknesh Updated it. Thank you for such a quick update. I am guessing I will need to reinstall the plugin if I want to get already synced files with the folder structure, right?

**Comment by marknesh** [comment]
You will have to delete the synced files in google drive and uninstall the extension.
Then install the extension and choose to upload existing files inorder to get the same folder structure for the existing files.

**Comment by marknesh** [comment]
@dasmeet I hope you managed to re-upload the existing files inorder to use the same folder structure.

**Comment by dasmeet** [comment]
@marknesh yes, it took a few days for all files to sync but seems to be working fine now. Thank you for your help!
