### ISSUE TITLE
Files not uploaded with exportToDrive when specifying Cloud Storage folder

### ISSUE THREAD

**Issue by jDrysdale** [marknesh/storage-googledrive-export#23]
Hello, when I specify a cloud storage folder path, new files are not uploaded to Google Drive.

Existing files are uploaded successfully on install, so I know the connection to Drive is working. New files are also copied successfully when no cloud storage folder path is specified.

Cloud storage folder path I'm using:
`customers/{UID}/images/`

When I add an image at the path `customers/{UID}/images/test.png`, it is not uploaded, and I see the message in the function logs:
Please upload files to one of the folder paths in (customers/{UID}/images/) as you specified in the Cloud Storage folder parameter, in order for the extension to work.

Using version 0.1.5.

I'm only specifying a single folder. I also tried entering 2 folder paths separated by a comma to no avail. I tried removing the trailing slash, and adding a heading slash too. Other settings:

BUCKET_NAME: default (verified it matches bucket for files after install completed)
FILE_TYPES: parameter not set
MAXIMUM_FILE_SIZE: parameter not set
UPLOAD_EXISTING_FILES: true
USE_FOLDER_STRUCTURE: false
LOCATION: us-central1 (same as rest of project)
Enable Events: false

Thanks so much for the amazing extension!

**Comment by marknesh** [comment]
Hi @jDrysdale, Dynamic folder paths are not supported in V0.1.5 , only static paths.

I will update this issue once it is implemented.

**Comment by jDrysdale** [comment]
Thanks for the reply! Just to clarify, I'm not expecting IDs to be injected into the path dynamically. When I enter the path in the configuration, I type out the full id in the path, like:

customers/12345/images/

Thanks again!

**Comment by marknesh** [comment]
I have reproduced the issue with the folder path `customers/12345/images/` and identified the bug causing the problem.

The fix will be included in the next version, plus support for dynamic paths. Thank you for bringing this to my attention.

**Comment by marknesh** [comment]
Hi @jDrysdale , I have fixed this issue and added support for dynamic folder paths. Please assist me in testing the new version of the extension by installing it using this  [link](https://console.firebase.google.com/u/0/project/_/extensions/install?ref=mark%2Fstorage-googledrive-export@2.0.0-rc.1) .

Remember to uninstall the previous version of the extension if it exists in the project before installing to avoid conflicts, thanks.

**Comment by jDrysdale** [comment]
Just tested, and this works great! Thank you!

For future users, the only point of confusion I had was using FOLDER_PATH without USE_FOLDER_STRUCTURE. I set it up that way to start, and saw the message in the exportToDrive function logs:

"You have set a folder path but the use folder structure configuration is still false, Please set it to true or leave the folder path empty"

I didn't realize USE_FOLDER_STRUCTURE is required when a FOLDER_PATH is present. I'd suggest updating the documentation to reflect this or allowing FOLDER_PATH to be off, so that it works the same way as when UPLOAD_EXISTING_FILES is on without USE_FOLDER_STRUCTURE -- the path gets added to the filename.

Thank you so much for the quick reply and fixes!

**Comment by marknesh** [comment]
> I didn't realize USE_FOLDER_STRUCTURE is required when a FOLDER_PATH is present. I'd suggest updating the documentation to reflect this or allowing FOLDER_PATH to be off, so that it works the same way as when UPLOAD_EXISTING_FILES is on without USE_FOLDER_STRUCTURE -- the path gets added to the filename.

Thank you for pointing that out. You're correct that USE_FOLDER_STRUCTURE and FOLDER_PATH should not depend on each other.

**Comment by jDrysdale** [comment]
@marknesh Confirming this fix worked on the 2.0.0-alpha.8 version. Thanks so much!
