### ISSUE TITLE
Files uploaded multiple times after uploadtoDriveOnInstall function timeout

### ISSUE THREAD

**Issue by jDrysdale** [marknesh/storage-googledrive-export#26]
When using this extension to copy on install, the uploadtoDriveOnInstall function timed out and then re-ran many times. I assumed it was uploading in batches and left it running, but just realized it seems to start the copy process over each time, resulting in the same images being uploaded repeatedly.

We have about 6 GB of images in storage right now. We ended up with 50+ duplicates of only a subset of the original images uploaded over the long weekend. The extension actually filled up a 30 GB drive account where the original images only take up 6 GB.

Sorry about all the reports — please let me know if there’s a way I can support the project & your ongoing work. I really appreciate it. Thanks!

**Comment by marknesh** [comment]
Hi @jDrysdale , I have fixed this issue. Please note that upload of large files exceeding the maximum timeout of a cloud function
of `540s` will not be uploaded. Read the **updated** installation [steps](https://github.com/marknesh/storage-googledrive-export/tree/refactor/dispatch-task-sequentially?tab=readme-ov-file#important-steps). Test the beta version [here](https://console.firebase.google.com/project/_/extensions/install?ref=mark/storage-googledrive-export@2.0.0-alpha.8)

**Comment by jDrysdale** [comment]
@marknesh thanks so much for this. I'll test first week of Jan 2025 and will report back. Happy holidays!

**Comment by jDrysdale** [comment]
@marknesh Confirming this fix also worked on the 2.0.0-alpha.8 version. Thanks so much!
