### ISSUE TITLE
Extension uses storage.admin when it should probably only require storage.objectAdmin

### ISSUE THREAD

**Issue by cabljac** [marknesh/storage-googledrive-export#3]
Currently the extension.yaml requires `storage.admin` which is a broad role, is there any reason it would need this over `storage.objectAdmin`?

As a general rule, published 3P extensions should use the narrowest sufficient roles.

**Comment by marknesh** [comment]
At first, I tried using `storage.objectAdmin` but I could not even get the default bucket because the extension did not have permission. So I used `storage.admin `and it worked.
